- hosts: all
  vars:
    ansible_port: 1467
    users:
      - Webdeveloper
      - Devopsengineer
      - Projectmanager
    passwords:
      - $1$suck$ySZ9.uy1/VXMCKUn3yo8i. 
      - $1$suck$FJuJ/UjRxp5RjimYA8N8i.
      - $1$suck$cM6P0VAecaqBdrhkLk1bJ0
  tasks:
    - name: copy      
      copy:
        content: |  
          module(load="imtcp")
          input(type="imtcp" port="514")
          if ($hostname == "Project2")
            then /var/log/project2.log
          if ($hostname == "Project3")
            then /var/log/project3.log
        dest: /etc/rsyslog.d/my.conf
      when: rsyslog == 'server'
    - copy: 
        content: |
          *.* @@192.168.100.20
        dest: /etc/rsyslog.d/my.conf
      when: rsyslog == 'client'
    - service:
        name: rsyslog
        state: restarted
    - name: Install curl
      apt:
        name: curl
        update_cache: yes
        state: present
    - name: timezone
      shell: timedatectl set-timezone Europe/Moscow
    - name: Enable ufw
      service:
        name: ufw
        state: started
        enabled: yes
    - name: allow ports
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - "80"
        - "8080"
        - "1467"
        - "514"
        - "3306"
    - name: install zabbix
      apt:
        name: zabbix-agent
        state: present 
      notify: disable zabbix
    - name: Create Users 1
      user:
        name: "{{ users[0] }}"
        password: "{{ passwords[0] }}"
    - name: Create Users 2
      user:
        name: "{{ users[1] }}"
        password: "{{ passwords[1] }}"
        groups: sudo
        append: yes
    - name: Create Users 3
      user:
        name: "{{ users[2] }}"
        password: "{{ passwords[2] }}"
    - name: add .ssh Dir
      file:
        state: directory
        path: "{{ item }}"
      loop: 
        - /home/{{ users[0] }}/.ssh
        - /home/{{ users[1] }}/.ssh
        - /home/{{ users[2] }}/.ssh
    - name: Add ssh keys
      copy:
        content: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCovvBkeLIDsvbCyQsMWtPWVgGVKcwAqRONiBJ9JyrVCQbruyMPutatjSlhNpYXKLlP4BXHrGrmAVqeI155li1fkNP5Il7viHRE0HvA3M2extNGDDCiX5f5OlIeT9p/D9OHvWWozLjN2NAGEW24feuzKPZb6Kyv2W3yHbiIU3wt8v50VAIA2+PAfElHp1jplGHQLmYuT6Cc26Pn3WYXZ8t8oU77T6Ki5qDG5V5DVZI3Ym5gqqXXtJYzET9piJvO6qiIcgljtOGlUH9H9QNLEbuF+RKIhL3pFAnF8S79Km2A3j9KFZw6prDR6/VeMffMrNSZLeYztzDGEzm35uz5q6j+qrKsuA4SfpbSOcBwaariOoKpb6JfogoJRgCqxR5O1AKR/Oqhdk6JOlKJk+tIXFmOczH7da/W93f8KGGve4iHRvz/e3vYA7exXIVkD8mc/VmIoT1kqh/uNGia/adnyCgvMpL8JXLJgY2DThpjHslUr0RTEpQJTLTka3D43YV37kM=
        dest: "{{ item }}"
      loop: 
        - /home/{{ users[0] }}/.ssh/authorized_keys
        - /home/{{ users[1] }}/.ssh/authorized_keys
        - /home/{{ users[2] }}/.ssh/authorized_keys
    - name: add gpg keys
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present
    - name: install docker
      apt:
        name: docker-ce
        state: present
    - name: enable and start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: download docker-compose
      uri:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
    - name: +x for docker-compose
      file:
        path: "/usr/local/bin/docker-compose"
        owner: root
        group: root
        mode: "0770"
    - name: create directory
      file:
        state: directory
        path: /skillcloud-nginx
    - name: touch files 1
      copy:
        content: |
          <html>
            <head>
              <title>SKILLCLOUD COMPANY</title>
            </head>
            <body>
              <h1>Hello Competitor</h1>
            </body>
          </html>
        dest: /skillcloud-nginx/index.html
    - name: touch files 2
      copy:
        content: | 
          worker_processes  auto;

          events {
          }


          http {
            upstream balance {
              server 192.168.100.10:8080;
              server 192.168.100.20:8080;
              server 192.168.100.30:8080;
            }

            server {
              listen 80;
              location / {
                proxy_pass http://balance;
              }
            }
          }
        dest: /skillcloud-nginx/nginx.conf
    - name: touch files 3
      copy:
        content: |
          FROM nginx

          COPY nginx.conf /etc/nginx/nginx.conf
        dest: /skillcloud-nginx/Dockerfile-balance
    - name: touch files 4
      copy:
        content: |
          FROM nginx
          
          COPY index.html /usr/share/nginx/html
        dest: /skillcloud-nginx/Dockerfile-site
    - name: touch files 5
      copy: 
        content: |
          version: "3.6"

          services:
            site:
              image: site:site
              container_name: site
              restart: always
              ports:
                - 8080:80

            balance:
              image: balance:balance
              container_name: balance
              restart: always
              ports:
                - 80:80
        dest: /skillcloud-nginx/docker-compose.yaml   
    - name: install fail2ban
      apt:
        name: fail2ban
        state: present
    - name: configure fail2ban
      copy:
        content: |
          [sshd]
          enabled = true
          bantime = 600
          findtime = 86400
          maxretry = 6
        dest: /etc/fail2ban/jail.d/defaults-debian.conf
      notify: restart fail2ban
    - name: Enable fail2ban
      service:
        name: fail2ban 
        state: started
        enabled: yes
    - name: download rsyslog
      apt:
        name: rsyslog
        state: latest
    - name: cron
      cron:
        name: hello
        job: /usr/bin/journalctl --vacuum-time=1month
        special_time: weekly
    - name: Restart
      reboot:
  handlers:
    - name: disable zabbix
      service:
        name: zabbix-agent
        state: stopped
    - name: restart fail2ban
      service: 
        name: fail2ban
        state: restarted
 
